[tool.poetry]
name = "luigi-docker"
version = "0.1.0"
description = "A simple docker build workflow"
authors = ["Fabien D."]

[tool.poetry.dependencies]
python = "^3.10"
luigi = "^3.0.3"
docker = "^5.0.3"
dependency-injector = "^4.37.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
